## Learning Numpy. The Hard Way. Part 3.

Вам нужно выполнить __последнюю часть__ упражнений по Numpy.


#### Задание 41.
```python
# Q. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

#### Задание 42.
```python
# Q. Randomly sample iris's species such that setose is twice the number of versicolor and virginica

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

#### Задание 43.
```python
# Q. What is the value of second longest petallength of species setosa

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

#### Задание 44.
```python
# Q. Sort the iris dataset based on sepallength column.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

#### Задание 45.
```python
# Q. Find the most frequent value of petal length (3rd column) in iris dataset.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

#### Задание 46.
```python
# Q. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.

# Input
# Use the iris dataset provided
print("Input")
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

#### Задание 47.
```python
# Q. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
# Input
print("Input")
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a

```

#### Задание 48.
```python
# Q. Get the positions of top 5 maximum values in a given array a.

# Input
print("Input")
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a
```

#### Задание 49.
```python
# Q. Compute the counts of unique values row-wise.

# Input
print("Input")
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

# Desired Output
# > [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
# >  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
# >  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
# >  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
# >  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
# >  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

# Output contains 10 columns representing numbers from 1 to 10. The values are the counts of the numbers in the respective rows.
# For example, Cell(0,2) has the value 2, which means, the number 3 occurs exactly 2 times in the 1st row.
```

#### Задание 50.
```python
# Q. Convert array_of_arrays into a flat linear 1d array.

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

#### Задание 51.
```python
# Q. Compute the one-hot encodings (dummy binary variables for each unique value in the array)

# Input
print("Input")
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

# Desired Output
# > array([[ 0.,  1.,  0.],
# >        [ 0.,  0.,  1.],
# >        [ 0.,  1.,  0.],
# >        [ 0.,  1.,  0.],
# >        [ 0.,  1.,  0.],
# >        [ 1.,  0.,  0.]])
```

#### Задание 52.
```python
# Q. Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.

# Input
# Use the iris dataset provided
print("Input")
print_files()

# Use this if you are working on your local machine
# species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
# species_small = np.sort(np.random.choice(species, size=20))
# species_small
# > array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
# >        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
# >        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
# >        'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
# >        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
# >        'Iris-virginica', 'Iris-virginica', 'Iris-virginica'],
# >       dtype='<U15')


# Desired Output
# > [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]
```

#### Задание 53.
```python
# Q. Create group ids based on a given categorical variable. Use the following sample from iris species as input

# Input
# Use the iris dataset provided
print("Input")
print_files()

# Use this if you are working on your local machine
# species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
# species_small = np.sort(np.random.choice(species, size=20))
# species_small
# > array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
# >        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
# >        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
# >        'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
# >        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
# >        'Iris-virginica', 'Iris-virginica', 'Iris-virginica'],
# >       dtype='<U15')

# Desired Output
# > [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]
```

#### Задание 54.
```python
# Q. Create the ranks for the given numeric array a.

# Input
print("Input")
np.random.seed(10)
a = np.random.randint(20, size=10)
a

# Desired Output
# [4 2 6 0 8 7 9 3 5 1]
```

#### Задание 55.
```python
# Q. Create a rank array of the same shape as a given numeric array a.

# Input
print("Input")
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
a

# Desired Output
# > [[4 2 6 0 8]
# >  [7 9 3 5 1]]
```

#### Задание 56.
```python
# Q. Compute the maximum for each row in the given array.

# Input
print("Input")
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
```

#### Задание 57.
```python
# Q. Compute the min-by-max for each row for given 2d numpy array.

# Input
print("Input")
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
```

#### Задание 58.
```python
# Q. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.

# Input
print("Input")
np.random.seed(100)
a = np.random.randint(0, 5, 10)
a

# Desired Output
# > [False  True False  True False False  True  True  True  True]
```

#### Задание 59.
```python
# Q. Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

# Input
# Use the iris dataset provided
print("Input")
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Desired Output
# > [[b'Iris-setosa', 3.418],
# >  [b'Iris-versicolor', 2.770],
# >  [b'Iris-virginica', 2.974]]
```

#### Задание 60.
```python
# Q. Import the image from the following URL and convert it to a numpy array.

# Input
print("Input")
print_files()

# Use this if you are working on your local machine
# URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
```

#### Задание 61.
```python
# Q. Drop all nan values from a 1D numpy array

# Input
print("Input")
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a

# Desired Output
# array([ 1.,  2.,  3.,  5.,  6.,  7.])
```

#### Задание 62.
```python
# Q. Compute the euclidean distance between two arrays a and b.

# Input
print("Input")
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
a
b
```

#### Задание 63.
```python
# Q. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

# Input
print("Input")
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
a

# Desired Output
# > array([2, 5])
# where, 2 and 5 are the positions of peak values 7 and 6.
```

#### Задание 64.
```python
# Q. Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.

# Input
print("Input")
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
a_2d
b_1d

# Desired Output
# > [[2 2 2]
# >  [2 2 2]
# >  [2 2 2]]
```

#### Задание 65.
```python
# Q. Find the index of 5th repetition of number 1 in x.

# Input
print("Input")
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
x
```

#### Задание 66.
```python
# Q. Convert numpy's datetime64 object to datetime's datetime object

# Input
print("Input")
dt64 = np.datetime64('2018-02-25 22:10:10')
dt64
```

#### Задание 67.
```python
# Q. Compute the moving average of window size 3, for the given 1D array.

# Input
print("Input")
np.random.seed(100)
a = np.random.randint(10, size=10)
a
```

#### Задание 68.
```python
# Q. Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers
```

#### Задание 69.
```python
# Q. Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling in the missing dates.

# Input
print("Input")
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
dates
```

#### Задание 70.
```python
# Q. From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

# Input
print("Input")
arr = np.arange(15) 
arr

# Desired Output
# > [[ 0  1  2  3]
# >  [ 2  3  4  5]
# >  [ 4  5  6  7]
# >  [ 6  7  8  9]
# >  [ 8  9 10 11]
# >  [10 11 12 13]]
```