## Learning Numpy. The Hard Way. 

Вам нужно выполнить упражнения по Numpy.


#### Задание 1.
```python
 # Q. Import numpy as np and print the version number.
```

#### Задание 2.
```python
# Q. Create a 1D array of numbers from 0 to 9

# Desired Output
# > array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

#### Задание 3.
```python
 # Q. Create a 3×3 numpy array of all True’s
```

#### Задание 4.
```python
# Q. Extract all odd numbers from arr
# Input 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Input")
arr

# Desired Output
# > array([1, 3, 5, 7, 9])
```

#### Задание 5.
```python
# Q. Replace all odd numbers in arr with -1
# Input 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Input")
arr

# Desired Output
# >  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

#### Задание 6.
```python
# Q. Replace all odd numbers in arr with -1 without changing arr
# Input 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Input")
arr

# Desired Output
# out #>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr #>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

#### Задание 7.
```python
# Q. Convert a 1D array to a 2D array with 2 rows
# Input 
arr = np.arange(10)
print("Input")
arr

# Desired Output
# > array([[0, 1, 2, 3, 4],
# >        [5, 6, 7, 8, 9]])
```

#### Задание 8.
```python
# Q. Stack arrays a and b vertically
# Input
print("Input")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
a
b

# Desired Output
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

#### Задание 9.
```python
# Q. Stack the arrays a and b horizontally.
# Input
print("Input")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Desired Output
# > array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
# >        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

#### Задание 10.
```python
# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input
print("Input")
a = np.array([1,2,3])
a

# Desired Output
# > array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

#### Задание 11.
```python
# Q. Get the common items between a and b

# Input
print("Input")
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a
b

# Desired Output
# array([2, 4])
```

#### Задание 12.
```python
# Q. From array a remove all items present in array b

# Input
print("Input")
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a
b

# Desired Output
# array([1,2,3,4])
```

#### Задание 13.
```python
# Q. Get the positions where elements of a and b match

# Input
print("Input")
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a
b

# Desired Output
# > (array([1, 3, 5, 7]),)
```

#### Задание 14.
```python
# Q. Get all items between 5 and 10 from a.

# Input
print("Input")
a = np.array([2, 6, 1, 9, 10, 3, 27])
a

# Desired Output
# (array([6, 9, 10]),)
```

#### Задание 15.
```python
# Q. Convert the function maxx that works on two scalars, to work on two arrays.

# Input

def maxx(x, y):
    """
    Get the maximum of two items
    """
    
    if x >= y:
        return x
    else:
        return y
print("Result of the maxx function")
maxx(1, 5)

print("Input")
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
a
b

# Desired Output
# pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

#### Задание 16.
```python
# Q. Swap columns 1 and 2 in the array arr.

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

#### Задание 17.
```python
# Q. Swap rows 1 and 2 in the array arr:

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

#### Задание 18.
```python
# Q. Reverse the rows of a 2D array arr.

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

#### Задание 19.
```python
# Q. Reverse the columns of a 2D array arr.

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

#### Задание 20.
```python
# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
```